fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run mypy docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: poetry run flake8 docling_core
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: poetry run pytest test/
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: docs
        name: Docs
        entry: poetry run generate_docs docs
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: poetry
        name: Poetry
        entry: poetry check --lock
        pass_filenames: false
        language: system
