name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "**"
      - "!gh-pages"

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  code-checks:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name != 'DS4SD/docling-core' && github.event.pull_request.head.repo.full_name != 'ds4sd/docling-core') }}
    uses: ./.github/workflows/checks.yml

    # To enable when we add the ./docs
  # build-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup-poetry
  #     - name: Build docs
  #       run: poetry run mkdocs build --verbose --clean
  
